version: "3.7"

services:
  app:
    build: .
    env_file:
      - .env
    ports:
      - 80:80
    volumes:
      - ./:/var/www/hmtl

  db:
    image: mariadb
    env_file:
      - .env
    ports:
      - 3306:3306
    volumes:
      - dbdata:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d/

volumes:
  dbdata:
    driver: local
